version: '3.8'
services:
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    ports:
      - '3306:3306'
    volumes:
      - ./src/database/mysql:/var/lib/mysql

  api:
    image: organize-desk-api-image
    container_name: organize-desk-api-container
    build: .
    ports:
      - '3000:3000'
    volumes:
      - .:/usr/app
    depends_on:
      - db
